version: '3.8'
services:
  app-node:
    build:
      context: .
    container_name: app-node 
    volumes:
      - ./:/usr/src/app
    # command: bash -c "npm run create:bid-table"
    ports:
      - "8080:5000"
    environment:
      PORT: 5000
      BID_TABLE_NAME: 'Bids'
      AWS_ENDPOINT: 'http://host.docker.internal:8000'
      AWS_ACCESS_KEY_ID: 'DUMMYIDEXAMPLE'
      AWS_SECRET_ACCESS_KEY: 'DUMMYEXAMPLEKEY'
      REGION: 'eu-west-1'